# TODO: refactor it

version: "3.7"
services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
    volumes:
      - real-world-app-api-db:/var/lib/postgresql/data
    # expose:
    #   - 5432

  real-world-app-api:
    build:
      context: .
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - DB_HOST=db
      - DB_USERNAME=${DB_USERNAME}
      - DB_DATABASE=${DB_DATABASE}
      - DB_TEST_DATABASE=${DB_TEST_DATABASE}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_LOGGING=${DB_LOGGING}
    depends_on:
      - db
    command: ./wait-for-it.sh postgres:5432 -- npm start
    ports:
      - "3000:3000"
volumes:
  real-world-app-api-db:
